# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MIT

"""picsonym: evocative, artistic titles for images via an LLM.

Titles are generated by a pluggable backend — by default,
:class:`OpenAIBackend` talks to an OpenAI-compatible chat completions API
(a local Ollama server unless `base_url` says otherwise). Implement
:class:`LLMBackend` yourself to run a model already loaded in-process
instead, e.g. inside a ComfyUI custom node.

Basic usage::

    >>> import picsonym
    >>> generator = picsonym.Picsonym(model="gemma4:e4b")  # doctest: +SKIP
    >>> generator.title_from_prompt("a lone lighthouse at dusk")  # doctest: +SKIP
    'Waiting For The Dark'
    >>> generator.rename_file("beach.jpg")  # doctest: +SKIP
    RenameResult(original=PosixPath('beach.jpg'), ...)
"""

from __future__ import annotations

from .backends import LLMBackend, OpenAIBackend
from .filenames import IMAGE_EXTENSIONS, sanitize_filename
from .images import normalize_image
from .renaming import Picsonym, RenameResult

__all__ = [
    "IMAGE_EXTENSIONS",
    "LLMBackend",
    "OpenAIBackend",
    "Picsonym",
    "RenameResult",
    "__version__",
    "normalize_image",
    "sanitize_filename",
]

__version__ = "1.0.0"
