# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: MIT

"""LLM-backed title generation.

Titles are generated by a pluggable :class:`~picsonym.backends.LLMBackend`
— an OpenAI-compatible chat completions API by default (OpenAI's own
cloud, a local Ollama server, or any other compatible endpoint), or a
custom backend running a model already loaded in-process. None of the
methods here are doctested: they perform a real API call, which would
either require network access or a local server at import/test time.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Final

import openai

from ._client import DEFAULT_BASE_URL
from .backends import (
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_TEMPERATURE,
    LLMBackend,
    OpenAIBackend,
)

__all__: list[str] = []

# The prompt asks for one 2-5 word title, but models don't always comply
# (e.g. drafting several candidates before hitting the token limit). This
# catches clearly malformed responses with generous slack above 5 words,
# rather than silently accepting a garbled multi-title string.
_MAX_TITLE_WORDS: Final = 8

_SYSTEM_PROMPT_FROM_PROMPT: Final = """\
You are an expert at titling artwork. You will be given a text prompt that \
was used to generate an image. Read the prompt and invent a single \
evocative, artistic title for the image it describes.

Focus on what the image is about: its mood, story, feeling, or situation. \
Do not describe how the image was made — avoid mentioning style, medium, \
technique, camera, lens, lighting, color palette, or artist names.

Output exactly one title, 2 to 5 words, in Title Case, written as a phrase \
(not a full sentence, no ending punctuation). Do not wrap it in quotation \
marks. Output only the title itself, with no explanation, preamble, or \
extra text.\
"""

_SYSTEM_PROMPT_FROM_IMAGE: Final = """\
You are an expert at titling artwork. You will be shown an image. Look at \
the image and invent a single evocative, artistic title for it.

Focus on what the image is about: its mood, story, feeling, or situation. \
Do not describe how the image was made — avoid mentioning style, medium, \
technique, camera, lens, lighting, color palette, or artist names.

Output exactly one title, 2 to 5 words, in Title Case, written as a phrase \
(not a full sentence, no ending punctuation). Do not wrap it in quotation \
marks. Output only the title itself, with no explanation, preamble, or \
extra text.\
"""

_IMAGE_USER_TEXT: Final = "Title this image."


def _clean_title(text: str) -> str:
    text = text.strip().strip("\"'").strip()
    return " ".join(text.split())


class _TitleGenerator:
    """Owns the title-generation prompts and delegates to an :class:`LLMBackend`."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        client: openai.OpenAI | None = None,
        model: str | None = None,
        temperature: float = DEFAULT_TEMPERATURE,
        max_output_tokens: int = DEFAULT_MAX_OUTPUT_TOKENS,
        backend: LLMBackend | None = None,
    ) -> None:
        """Construct a title generator.

        :param api_key: Forwarded to the default :class:`OpenAIBackend`.
            Ignored if `backend` is given.
        :param base_url: Forwarded to the default :class:`OpenAIBackend`.
            Ignored if `backend` is given.
        :param client: Forwarded to the default :class:`OpenAIBackend` as
            its `client`. Ignored if `backend` is given.
        :param model: Model name for the default :class:`OpenAIBackend`;
            must be vision-capable to use :meth:`title_from_image`.
            Required unless `backend` is given — no model is universally
            available on a local Ollama install, and guessing one would
            fail confusingly at API-call time instead of clearly at
            construction time.
        :param temperature: Forwarded to the default :class:`OpenAIBackend`.
            Ignored if `backend` is given.
        :param max_output_tokens: Forwarded to the default
            :class:`OpenAIBackend`. Ignored if `backend` is given.
        :param backend: A custom :class:`LLMBackend` — e.g. one running a
            model already loaded in-process, with no HTTP call involved.
            When given, `api_key`/`base_url`/`client`/`model`/`temperature`/
            `max_output_tokens` are all ignored, since the backend already
            encapsulates how (and against what model) it generates text.
        :raises ValueError: if `backend` is not given and `model` is None.
        :raises openai.OpenAIError: see :class:`OpenAIBackend`.
        """
        if backend is not None:
            self._backend = backend
        else:
            if model is None:
                raise ValueError("model is required when no backend is given")
            self._backend = OpenAIBackend(
                api_key=api_key,
                base_url=base_url,
                client=client,
                model=model,
                temperature=temperature,
                max_output_tokens=max_output_tokens,
            )

    def _complete(
        self, *, system_prompt: str, user_text: str, image: bytes | None
    ) -> str:
        content = self._backend.generate(
            system_prompt=system_prompt, user_text=user_text, image=image
        )
        if not isinstance(content, str):
            backend_name = type(self._backend).__name__
            raise TypeError(
                f"{backend_name}.generate() must return str, "
                f"got {type(content).__name__}"
            )
        if not content.strip():
            raise RuntimeError("the backend returned no title content")
        title = _clean_title(content)
        if len(title.split()) > _MAX_TITLE_WORDS:
            raise RuntimeError(f"the backend returned a malformed title: {title!r}")
        return title

    def title_from_prompt(self, prompt: str) -> str:
        """Generate a title from a text image-generation prompt.

        :param prompt: The prompt originally used to generate an image.
        :returns: A clean, human-readable title (a Title Case phrase) —
            not yet filename-sanitized.
        :raises ValueError: if `prompt` is empty or blank.
        :raises TypeError: if the backend does not return a str.
        :raises RuntimeError: if the backend returns no usable content, or
            a malformed (too many words) title.
        """
        if not prompt.strip():
            raise ValueError("prompt must not be empty")
        return self._complete(
            system_prompt=_SYSTEM_PROMPT_FROM_PROMPT, user_text=prompt, image=None
        )

    def title_from_image(self, image: str | os.PathLike[str] | bytes) -> str:
        """Generate a title by looking at an image's content.

        :param image: Path to an image file, or raw image bytes.
        :returns: A clean, human-readable title — not yet filename-sanitized.
        :raises ValueError: if the backend cannot make sense of the image
            data (e.g. the default :class:`OpenAIBackend` requires a
            format Pillow can decode).
        :raises FileNotFoundError: `image` is a path that does not exist.
        :raises TypeError: if the backend does not return a str.
        :raises RuntimeError: if the backend returns no usable content, or
            a malformed (too many words) title.
        """
        data = image if isinstance(image, bytes) else Path(image).read_bytes()
        return self._complete(
            system_prompt=_SYSTEM_PROMPT_FROM_IMAGE,
            user_text=_IMAGE_USER_TEXT,
            image=data,
        )
